### ISSUE TITLE
use /run for wabashd.exe.lock

### ISSUE THREAD

**Issue by heldchen** [cerebrate/wabashd#1]
the lockfile `wabashd.exe.lock` should be created in the /run directory. this directory is purged when WSL tears down the processes, unlike /tmp where files persist. 

when logging out of the windows user account without closing wabash first, or when the pc or bash crashes, the lock file currently remains in /tmp and prevents a successful next start of wabash. moving the lockfile to /run solves this automatically.

**Comment by cerebrate** [comment]
Thanks muchly for the pointer; I wasn't aware of /run.

Fixed in wabashd 6, in the repository now.

**Comment by heldchen** [comment]
awesome, works nicely, thanks!
