### ISSUE TITLE
bash variant of the daemon

### ISSUE THREAD

**Issue by heldchen** [cerebrate/wabashd#2]
here's a shell version of the deamon that has no extra dependencies, with the additional benefit of not needing a pid lock file. this is a replacement for `/usr/bin/start-wabashd`

```
#!/bin/bash

version=4
shell=/bin/bash
interval=2

function tick()
{
        local sess=0
        local daem=0

        while read -r proc; do
                if [ "$proc" == "init" ] || [ "$proc" == "bash" ] ; then
                        sess=$((sess + 1))
                else
                        daem=$((daem + 1))
                fi
        done <<< "$(ps --ppid 1 --no-headers -o comm)"

        echo "sess: $sess daem: $daem"
}

function strt()
{
        local svcname=$1

        if [ "$svcname" = "" ] ; then
                echo "svup error: service name missing"
                return
        fi

        local output="$(/usr/bin/sudo /usr/sbin/service $svcname start 2>&1)"

        if [ "$output" = "" ] ; then
                echo "svup ${svcname} has no output"
        else
                echo "svup " "$output" | head -n 1
        fi
}

function handle_input()
{
        local actions
        local action
        local params

        read -e -s -t 0 && read -e -s actions
        if [ "$actions" != "" ] ; then
                # remove windows' CR
                actions="${actions//[$'\r']}"

                while read -r command; do
                        action="${command:0:4}"
                        params="${command:5}"

                        case "$action" in
                                stop)
                                        echo "stop"
                                        exit 0
                                        ;;
                                strt)
                                        strt "$params"
                                        ;;
                                ping)
                                        echo "pong"
                                        ;;
                                *)
                                        echo "error"
                        esac
                done <<< "${actions}"
        fi
}

echo "shell: ${shell}"
echo "version: ${version}"
while true; do
        handle_input
        tick
        sleep $interval
done
```

**Comment by heldchen** [comment]
Wabash (the windows client part) dies when the daemon returns `error ...`  or `serror ...` responses. to ease the setup, I've therefore prefixed the `strt` error messages with `svup ` so Bash doesn't die instantly.

**Comment by cerebrate** [comment]
Shiny!

I'm not going to make it the canonical wabashd, though, I'm afraid, since the reason I wrote it using mono in the first place was to keep it in my native tongue, as it were: while I can muddle my way through shell scripting, I'm not comfortable enough in it to support a shell wabashd myself.

If you feel like packaging it up yourself, though, I'd be more'n happy to add "wabashd-shell" to the wsl-translinux repository and include a pointer to it in the wabash docs.

**Comment by cerebrate** [comment]
For reference, incidentally, my roadmap for wabashd going forward is to move it to .NET Core rather than mono, which should at least be lighter-weight, dependency-wise.

**Comment by heldchen** [comment]
>  I can muddle my way through shell scripting, I'm not comfortable enough in it to support a shell wabashd myself.

I totally understand. I took it as an exercise to brush up my shell scripting :-)

> If you feel like packaging it up yourself, though, I'd be more'n happy to add "wabashd-shell" to the wsl-translinux repository and include a pointer to it in the wabash docs.

good idea. I'll learn how to do debian packaging and submit it to the translinux repository.

**Comment by heldchen** [comment]
created https://github.com/cerebrate/wsl-translinux/pull/2 

I hope I did everything correct, it's my first debian package and my first PR on github :-). if something is not right let me know in the PR. closing this issue here.
